#pragma once

#include <linux/if_ether.h>
#include <linux/types.h>

enum {
    RX_QUEUE_BYTES = 4U,
    ETH_HEADER_BYTES = ETH_HLEN,
    ARPHRD_ETHER_BPF = 1U,
    ARP_HEADER_BYTES = 28U,
    ARP_HW_TYPE_OFFSET = 0U,
    ARP_PROTO_TYPE_OFFSET = 2U,
    ARP_HW_LEN_OFFSET = 4U,
    ARP_PROTO_LEN_OFFSET = 5U,
    ARP_SENDER_MAC_OFFSET = 8U,
    ARP_IPV4_PROTO_LEN = 4U,
    ARP_SRC_IP_OFFSET = 14U,
    ARP_TARGET_MAC_OFFSET = 18U,
    ARP_DST_IP_OFFSET = 24U,

    ETH_PROTO_OFFSET = 12U,

    IPV4_MIN_IHL_WORDS = 5U,
    IPV4_IHL_MASK = 0x0FU,
    IPV4_IHL_WORD_BYTES = 4U,
    IPV4_MIN_HEADER_BYTES = 20U,
    IPV4_PROTO_OFFSET = 9U,
    IPV4_SRC_ADDR_OFFSET = 12U,
    IPV4_DST_ADDR_OFFSET = 16U,
    IPV4_ADDR_BYTES = 4U,
    IPV4_SLICE_OFFSET = 8U,
    IPV4_SLICE_BYTES = 12U,
    IPV4_SLICE_PROTO_OFFSET = IPV4_PROTO_OFFSET - IPV4_SLICE_OFFSET,
    IPV4_SLICE_SRC_IP_OFFSET = IPV4_SRC_ADDR_OFFSET - IPV4_SLICE_OFFSET,
    IPV4_SLICE_DST_IP_OFFSET = IPV4_DST_ADDR_OFFSET - IPV4_SLICE_OFFSET,

    IPV6_HEADER_BYTES = 40U,
    IPV6_PROTO_OFFSET = 6U,
    IPV6_SRC_ADDR_OFFSET = 8U,
    IPV6_DST_ADDR_OFFSET = 24U,
    IPV6_ADDR_BYTES = 16U,
    IPV6_SLICE_OFFSET = IPV6_PROTO_OFFSET,
    IPV6_SLICE_BYTES = 34U,
    IPV6_SLICE_PROTO_OFFSET = 0U,
    IPV6_SLICE_SRC_IP_OFFSET = IPV6_SRC_ADDR_OFFSET - IPV6_SLICE_OFFSET,
    IPV6_SLICE_DST_IP_OFFSET = IPV6_DST_ADDR_OFFSET - IPV6_SLICE_OFFSET,

    ARP_SLICE_OFFSET = ARP_SRC_IP_OFFSET,
    ARP_SLICE_BYTES = 14U,
    ARP_SLICE_SRC_IP_OFFSET = 0U,
    ARP_SLICE_DST_IP_OFFSET = ARP_DST_IP_OFFSET - ARP_SLICE_OFFSET,

    IP_STORAGE_SIZE = IPV6_ADDR_BYTES
};

